imflip		:	imflip.c ImageStuff.c ImageStuff.h
				gcc imflip.c ImageStuff.c -o imflip

imflipP		:	imflipP.c ImageStuff.c ImageStuff.h
				gcc imflipP.c ImageStuff.c -o imflipP -lpthread

imflipPg	:	imflipPg.c ImageStuff.c ImageStuff.h
				gcc imflipPg.c ImageStuff.c -o imflipPg -lpthread


prime       :    prime.c
				 gcc prime.c -o prime

primeP      :	 primeP.c
				 gcc primeP.c -o primeP -lpthread

primePC     :    primePC.c
				 gcc primePC.c -o primePC -lpthread

