imadd		:	imadd.c ImageStuff.c ImageStuff.h
				gcc imadd.c ImageStuff.c -o imadd -lpthread

imflip		:	imflip.c ImageStuff.c ImageStuff.h
				gcc imflip.c ImageStuff.c -o imflip

imflipP		:	imflipP.c ImageStuff.c ImageStuff.h
				gcc imflipP.c ImageStuff.c -o imflipP -lpthread


imflipPM	:	imflipPM.c ImageStuff.c ImageStuff.h
				gcc imflipPM.c ImageStuff.c -o imflipPM -lpthread
				
imflipPMC	:	imflipPMC.c ImageStuff.c ImageStuff.h
				gcc imflipPMC.c ImageStuff.c -o imflipPMC -lpthread

imrotate	:	imrotate.c ImageStuff.c ImageStuff.h
				gcc imrotate.c ImageStuff.c -o imrotate -lpthread

imrotateMC	:	imrotateMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMC.c ImageStuff.c -o imrotateMC -lpthread

imrotateMMC	:	imrotateMMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMMC.c ImageStuff.c -o imrotateMMC -lpthread
				
				
				
